### ISSUE TITLE
Please update version 1.20.1

### ISSUE THREAD

**Issue by safesaffawa** [charassss/tin3o#2]
Sorry for the server-side problem I needed to solve with it.
Thanks!

**Comment by safesaffawa** [comment]
Recompile to 1.20.x
Version 1.2.0
[TIN3O-1.2.0.jar.zip](https://github.com/charassss/tin3o/files/12137491/TIN3O-1.2.0.jar.zip)
Please change to .jar

**Comment by MSDNicrosoft** [comment]
The latest release works in 1.20.x.
It needn't to update.
